services:
  mongo:
    image: mongo
    container_name: task-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - task-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - task-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0  # Use a specific version
    container_name: task-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_PROCESS_ROLES: ""  # Disables KRaft mode
    depends_on:
      - zookeeper
    networks:
      - task-net

  redpanda-console:
    image: redpandadata/console:latest
    container_name: task-redpanda-console
    ports:
      - "8082:8080"
    environment:
      KAFKA_BROKERS: kafka:9092
    networks:
      - task-net
    depends_on:
      - kafka

volumes:
  mongo-data:

networks:
  task-net:
    external: true