services:
  file-management:
    build: .
    container_name: file-management-service
    ports:
      - "${APP_PORT}:${DOCKER_PORT}"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - task-net
networks:
  task-net:
     external: true